include/hasp_conf.h, src/hasp_debug.cpp, src/hasp_dispatch.cpp, src/hasp_gpio.cpp, src/hasp_gui.cpp, src/hasp_slave.cpp, src/hasp_slave.h, src/main.cpp
=> Initital Tasmotaslave support

user_setups/esp32/lanbon_l8.ini, user_setups/lcd_config.ini
=> my working Lanbon L8 config

src/svc/hasp_mqtt_ha.cpp
=> add missing json attributes

src/drv/hasp_drv_touch.cpp, src/drv/touch/hasp_drv_stmpe610.cpp, src/drv/touch/hasp_drv_stmpe610.h
=> add stmpe610 touch driver

src/dev/posix/hasp_posix.cpp, src/drv/tft_driver_sdl2.h, tools/osx_build_extra.py, tools/osx_build_script.py, user_setups/darwin_sdl/darwin_sdl_64bits.ini
Not sure why backlight and title don't work in MacOS
=> add support for emulator in darwin (MacOS) 

src/dev/esp8266/esp8266.cpp, src/dev/esp8266/esp8266.h, src/hasp/hasp_attribute.cpp, src/hasp/hasp_dispatch.cpp
fix esp8266 core status message
closes#103 update to min max attribute setting
=> 0.4.0 dev tweaks

.gitpod.Dockerfile, .gitpod.yml
After merging this, I'll add to the docs the few easy steps to create own build based on gitpod.
=> Add gitpod build environment for almost oneclick builds

.github/workflows/build.yaml, .github/workflows/release.yml
Add lolin-d32-pro_ili9341 to Github build scripts
=> Add lolin-d32-pro_ili9341

platformio_override-template.ini, user_setups/esp32/ttgo-esp32_tdisplay_v1.ini
as subject states. simple update
=> added compile template for TTGO T-Display v1 (esp32 version)

src/mqtt/hasp_mqtt_esp.cpp
Fixed issue when HASP_USE_CUSTOM is defined
=> Fix custom topic

user_setups/esp32/esp32-2432s032.ini
Add support for Sunton ESP32-2432S032C
=> Add Sunton ESP32-2432S032C

src/drv/tft/tft_driver_lovyangfx.cpp, user_setups/esp32s3/esp-box.ini
This adds the TT21100 touch driver used by the ESP-BOX, and adds a preset for the ESP-BOX.
=> Support ESP-BOX

lib/lv_lib_qrcode/lv_qrcode.c, lib/lv_lib_qrcode/lv_qrcode.h, lib/lv_lib_qrcode/qrcodegen.cpp, lib/lv_lib_qrcode/qrcodegen.h, src/hasp/hasp_attribute.cpp, src/hasp/hasp_attribute_helper.h, src/hasp/hasp_event.cpp, src/hasp/hasp_object.cpp, src/hasp/hasp_object.h, src/hasplib.h
Add QR-code object
Example
{"page":1,"id":42,"obj":"qrcode","text":"www.openhasp.com/0.7.0/design/objects/","x":520,"y":20,"size":200}
=> Add QR-code object

lib/lv_lib_qrcode/lv_qrcode.c, src/hasp/hasp_object.cpp
fix: improve memory leaks on delete
=> fix: improve memory leaks on delete qrcode

src/mqtt/hasp_mqtt_esp.cpp
issues #697
https://github.com/HASwitchPlate/openHASP/issues/697
=> fix: Custom Group Topic name does not work

src/hasp_filesystem.cpp
Trivial change that doesn't affect the code.
=> Minor spelling mistake corrected

user_setups/esp32s3/ws_esp32_s3_touch_lcd_4p3.ini
Add support for Waveshare ESP32-S3-Touch-LCD-4.3 from https://github.com/HASwitchPlate/openHASP/discussions/602
=> Add support for Waveshare ESP32-S3-Touch-LCD-4.3

src/drv/tft/tft_driver_arduinogfx.cpp, src/sys/svc/hasp_http_async.cpp, user_setups/esp32s3/lilygo-t-panel.ini
This pull request adds the pinmap and basic driver libraries for the Lilygo T-Panel v1.2 to openHASP. The pinout diagrams are included for easy reference.
> Note: This is a Work-In-Progress (WIP) release and the touchscreen functionality is still not implemented.
https://www.lilygo.cc/products/t-panel-s3
Added Lilygo T-Panel v1.2 pinmap
Provided basic driver libraries
Pinout diagrams for easy reference
=> Add Lilygo T-Panel v1.2 Pinmap and Drivers (WIP, Touchscreen not implemented)

src/drv/tft/tft_driver_lovyangfx.cpp, user_setups/esp32/esp32-2432s022c.ini
This is the device
https://www.aliexpress.com/item/1005006284129428.html
This unit also have sound output but I'm not certain if openHASP even supports it.
This fixes issue #606
=> Initial support for Guition ESP32-2432S022C

user_setups/esp32s3/sunton-esp32-s3-tft.ini
See https://github.com/HASwitchPlate/openHASP/issues/868 and https://github.com/HASwitchPlate/openHASP/discussions/861
=> Tweak settings for ESP32-8048S050 so that display works.
