HASwitchPlate/openHASP

src/net/hasp_wifi.cpp

Allow the WiFi key to be the maximum 64 characters supported by the standard.

Allow long wifi passwords

---

src/sys/svc/hasp_http.cpp

Will allow for user configurable templates.
for example:
```
// Dark theme
#define D_HTTP_COLOR_TEXT               "#eaeaea"    // Global text color - Very light gray
#define D_HTTP_COLOR_BACKGROUND         "#252525"    // Global background color - Very dark gray (mostly black)
#define D_HTTP_COLOR_INPUT_TEXT         "#000"       // Input text color - Black
#define D_HTTP_COLOR_INPUT              "#ddd"       // Input background color - Very light gray
#define D_HTTP_COLOR_INPUT_WARNING      "#ff5661"    // Warning text color - Brick Red
#define D_HTTP_COLOR_BUTTON_TEXT        "#faffff"    // Button text color - Very pale (mostly white) cyan
#define D_HTTP_COLOR_BUTTON             "#1fa3ec"    // Button color - Vivid blue
#define D_HTTP_COLOR_BUTTON_RESET       "#d43535"    // …
```

web page color scheme via user_config_override.h

---

src/hasp_config.cpp
src/hasp_config.h

Makes it possible to define the GPIO config through `user_config_override.h`
`#define HASP_GPIO_TEMPLATE "[2360346,2491680,2623009,2097420,2097678,2097947,0,0]"`

allow gpio template via user_config_override

---

src/hasp/hasp_dispatch.cpp
src/hasp/hasp_dispatch.h
src/hasp_config.cpp

update to re-use existing functions.
define `HASP_GPIO_TEMPLATE` in `user_config_override.h`
`#define HASP_GPIO_TEMPLATE "[2097433,2097691,2097952,131361,131619,0,0,0]"`

gpio template via user_config_override

---

src/sys/svc/hasp_http.cpp

In this commit I changed the httpsetup and httploop functions and added webHandleCaptivePortalWifiConfig to send the wifi config page when a device connects to the softAP. 
This will simplify the innitial wifi setup. The user can just scan the QR code and a webpage will automatically appear without the need to enter the IP address.

added Captive Portal functionality

---

platformio_override-template.ini
src/drv/old/hasp_drv_analogTouch.h
src/drv/touch/touch_driver.h
src/drv/touch/touch_driver_analog.h
user_setups/esp32/esp32-ili9341-unoshield-analog.ini

I have added an analog touch driver for integrating the ESP32 with those ubiquitous [arduino uno shields](http://www.lcdwiki.com/2.4inch_Arduino_Display) that have no integrated touchscreen controller
The only additional requirement is to use two other pins (that must be connected to ADC1 of the ESP32) in parallel with TFT_DC and TFT_WR pins. 
I included another user setup with the pinout and configs I tested.

ILI9341 unoshield with analog touch implementation

---

user_setups/esp32/_esp32.ini

based on idf44 and arduino commits from 24 Feb.
Probably very close to the upcoming core 2.0.3
Greetings from Tasmota team :-)
Solo1 build is updated too. 
https://github.com/tasmota/platform-espressif32/releases/download/v2.0.2.3/platform-espressif32-2.0.2.3solo1.zip

Tasmota core 2.0.2.3

---

include/hasp_conf.h
lib/ETHSPI/ETHSPI.cpp
lib/ETHSPI/ETHSPI.h
src/hasp_oobe.cpp
src/main_arduino.cpp
src/sys/net/hasp_ethernet_spi.cpp
src/sys/net/hasp_ethernet_spi.h
src/sys/net/hasp_network.cpp
src/sys/net/hasp_network.h
src/sys/net/hasp_wifi.cpp
src/sys/net/hasp_wifi.h
src/sys/svc/hasp_http.cpp
user_setups/esp32/lanbon_l8_eth.ini

Additional files and configuration to build W5500 SPI Ethernet functionality, along with a a lanbon build options ini file

Add W5500 SPI Ethernet 

---

src/sys/net/hasp_ethernet_esp32.cpp

Called the new functions network_connected() and network_disconnected() instead of directly calling networkStart() and networkStop(). 
This accounts for the change to networkEvery5Seconds() which no longer directly checks for the ethernet connection status. 
So now MQTT will connect as it should

Make MQTT work with Ethernet

---

src/hasp_filesystem.cpp

Added the following defines to allow auto creation of missing files during file system creation (after a factory reset)
HASP_BOOT_CMD
HASP_MQTT_ON_CMD
HASP_MQTT_OFF_CMD

Add option to auto create other standard files

---

src/hasp/hasp_attribute.cpp
src/hasp/hasp_attribute.h
src/hasp/hasp_event.cpp

1. Add support for new attributes:
-  `mode` is a read/write attribute which has a value of `hue`, `saturation`, or `value` and exposes `lv_cpicker_get_color_mode`/`lv_cpicker_set_color_mode`.
- `mode_fixed` is a read/write Boolean attribute and exposes `lv_cpicker_get_color_mode_fixed`/`lv_cpicker_set_color_mode_fixed`
2. MQTT status responses include `h`, `s`, and `v` attributes from `cpicker`.
``` json
{
"id": 4,
"parentid": 2,
"obj": "cpicker",
"x": 25,
"y": 5,
"w": 180,
"h": 180,
"mode_fixed": true
}
```

Improve cpicker in two ways

---

CHANGELOG.md

Fix some very minor issues with the changelog, the most important of which is... the filename :)

Spelling fixes (changelog)

---

.github/workflows/build.yaml
.github/workflows/release.yml
platformio_override-template.ini
user_setups/esp32/makerfabs-tft35-cap.ini

My Makerfabs ESP32 TFT Touch, v1.1 on the silkscreen, purchased in October 2020, has a 4MB flash as reported by esptool flash_id:
Manufacturer: 20
Device: 4016
Detected flash size: 4MB
Add a makerfabs-tft35-cap_4MB variant, and rename makerfabs-tft35-cap to makerfabs-tft35-cap_16MB.

Add 4MB variant for Makerfabs ESP32 TFT Touch

---

src/hasp/hasp_dispatch.cpp

Adding additional system scripts that are automatically executed when the idle level is changed.
* idle_off.cmd
* idle_short.cmd
* idle_long.cmd
In example this scripts can use to easy control the backlight or change page
* idle_off.cmd
```
backlight {"state": true, "brightness": 255}
moodlight {"state": false}
```
* idle_short.cmd
```
backlight {"state": "on", "brightness": 50}
```
* idle_long.cmd
```
backlight {"state": false, "brightness": 5}
moodlight {"state": true, "color":"green"}
```

Adding system scripts that are automatically executed when idle level is changed

---

src/drv/tft/tft_driver_lovyangfx.cpp

Fix for #534
After compiling at least now openHASP starts 👍 and I can access over WIFI.
I still have issues with this driver, only tft_espi works but that is not related to this fatal error.

Fix #534 ILI9486 Failed to start: src/drv/tft/tft_driver_lovyangfx.cpp

---

src/hasp_oobe.cpp

In https://github.com/HASwitchPlate/openHASP/pull/71 support for longer WiFi passwords was introduced but it was not extended to the GUI editor which is still limited to 32 characters. Tested, works :)

Allow long WiFi passwords in the GUI

---

src/hasp_config.cpp
src/hasp_config.h
src/sys/svc/hasp_http.cpp
src/sys/svc/hasp_http_async.cpp

The problem was detected in configSetup() - the configuration was read only from EEPROM but not from SPI flash FS.
Cleanup things and use only one allocation size for both write and read configuration operations.

use one allocation size for DynamicJsonDocument settings

---

platformio_override-template.ini
user_setups/esp32/wz2432r028.ini

Tested, working well. https://www.elecrow.com/esp32-display-2-8-inch-hmi-display-spi-tft-lcd-touch-screen.html

Added support for Wizee (Elecrow) 2.8 WZ2432R028 ESP32 Display

---

tools/osx_build_extra.py
user_setups/darwin_sdl/darwin_sdl_64bits.ini

Fix mac build:
- Change compiler version so it works with newer MacOS
- Fix library paths
- Exclude freetype which creates a build error

Fix MacOS build

---

user_setups/esp32/huzzah32-v2-featherwing-24-v2.ini
user_setups/esp32/huzzah32-v2-featherwing-35-v2.ini

Corrected typos in the environment names which caused the tests to fail.

Corrected environment names for huzzah32-v2-* boards

---

src/hasp/hasp.cpp
src/hasp/hasp_attribute.cpp

When specifying a URL for image src, we get a timeout already after 1 second. Some image providers (like security cameras) are taking more than 1 second. This simple change solves that.
(sorry for the 2 extra commits, mixed up branches)

Allow more time for http get

---

src/hasp/hasp.cpp

See https://github.com/HASwitchPlate/openHASP/issues/618
The idle scripts were inoperative since a recent commit.
Not sure if what I claim is true, but this is my interpretation: Since:
* ```dispatch_idle_state()``` seems to be called also when a state situation is requested (```dispatch_current_state()```)
* ```dispatch_idle()``` seems to be called only upon startup
* ```hasp_set_sleep_state()``` seems to be deprecated
and we want the scripts to be called only when the state changes, I decided to put the scripts directly in the function that detects the changes: ```hasp_update_sleep_state()```

re-enable idle scripts

---

src/dev/esp32/esp32.cpp
src/dev/esp32/esp32.h

This creates a smooth but fast backlight transition, fading to the new level in 200 milliseconds.  Tested on sunton-8048s050c_16MB.

On ESP32 fade the backlight

---

src/sys/net/hasp_wireguard.cpp
src/sys/svc/hasp_http.cpp

WireGuard-ESP32 library uses lwip_getaddrinfo() call to resolve IP/hostname string, so it should work.

wireguard - allow to set hostname for the remote peer

---

src/lang/lang.h
src/sys/net/hasp_wireguard.cpp
src/sys/svc/hasp_http.cpp

- accept the password mask as valid input string in web ui
- do not set the new configuration immediatelly (use manual restart like for wifi)

Little wireguard cleanups

---

src/hasp_debug.cpp
src/main_pc.cpp
tools/osx_build_extra.py

Recently https://github.com/HASwitchPlate/openHASP/pull/631 broke Darwin build
This PR fixes the situation and upgrades to MacOS 14 (Sonoma)

Fix to compile in MacOS 14

---

src/hasp/lv_theme_hasp.c

It does not so look really cool to have gradient and border in the dark screen background. Use just plain dark, but keep background gradient for widgets.
proposed
current

hasp dark theme - use black (no gradient) for the background

---

include/lv_conf_v7.h
include/lv_conf_v8.h

Right now, it is not possible to use `user_config_override.h` to set `#define LV_MEM_CUSTOM 1`.  Both `lv_conf_v7.h` and `lv_conf_v8.h` force the value to 0.
This PR makes it possible to override the value of LV_MEM_CUSTOM.
See the discussion around https://github.com/HASwitchPlate/openHASP/issues/676 for example.

Allow overriding of LV_MEM_CUSTOM

---

src/drv/tft/tft_driver_arduinogfx.cpp

On my Guiton 4", most of the gpio pins are assigned to the display and can not be used for input/output.
This change hides these pins in the web interface.

Add list of TFT gpio pins so that they can not be selected for IO.

---

src/hasp/hasp_parser.cpp

Started using the format_bytes function with some real big numbers. Noted that the numbers were not being converted from MB to GB before being printed.

Missing the FILE_SIZE_DIVIDER for gigabits

---

src/hasp/hasp_parser.cpp
src/hasp/hasp_parser.h

When dealing with SD cards we could be asked to print a uint64 (for example, from SD.totalGytes()).
This attempt to handle the very large numbers that might be expected from an SD card.
Yes, there is a bit of ugliness from recasting to a uint32 before calling the snprintf function, but this avoids implicit casts where data could be truncated.

Using size_t limits max number to 2^32. 

---

src/drv/tft/tft_driver_arduinogfx.cpp
user_setups/esp32s3/esp32-s3-4848S040.ini

Forgot to include the TFT_G5 GPIO pin in the is_driver_pin() list.
Whilst at it, include the USB TX/RX pins for the Guition ESP32-S3 4848S040 board. These two pins are wired to a CH340C chip, so not available for other uses.

Hide TFT-G5 & USB GPIO pins in web page

---

src/drv/tft/tft_driver_arduinogfx.cpp

Realised there is a is_system_pi() function - The USB TX/RX pins are better off there rather than hijacking the is_driver_pin() function.

Move USB_TXD/RXD to is_system_pin()

---

.devcontainer/devcontainer.json
.github/dependabot.yml
platformio_override-template.ini

Hi,
thanks for the project, it seems the only one currently able to run on my panlee device.
I struggled to install all the dependencies and make platformio work on my fedora laptop, so I ended up managing to do it with the devcontainers. Here's my contribution back to the community, for once :)
Notes:
- I kept all the default comments, but can strip them out if a cleaner file is preferred
- It automatically created the dependabot, again, can remove it if not needed, but I preferred to ask rather than just omit it
- Added the panlee devices (and instruction on where to find more) in the template, as I didn't understand I had to add them there. In hindsight this was more obvious, but it's my first time messing with platformio, and maybe I'm not the only one

Add devcontainer configuration

---

src/sys/gpio/hasp_gpio.cpp
src/sys/gpio/hasp_gpio.h
src/sys/svc/hasp_http.cpp
src/sys/svc/hasp_http_async.cpp
user_setups/esp32/huzzah32-v2-featherwing-35-v2.ini

* The board of "env:huzzah32-v2-featherwing-35-v2" was changed to adafruit_feather_esp32_v2
Previously it was pointing to the v1 board. See also:
V1: https://github.com/platformio/platform-espressif32/blob/develop/boards/featheresp32.json
V2: https://github.com/platformio/platform-espressif32/blob/develop/boards/adafruit_feather_esp32_v2.json
* Fixed the port numbers
* hasp_gpio_type_t::BUTTON had to be renamed because adafruit_feather_esp32_v2/pins_arduino.h defines a macro named BUTTON.

Fix support for Adafruit HUZZAH32 V2 ESP32 Featherwing 3.5 V2

---

src/drv/tft/tft_defines.h
src/drv/tft/tft_driver_lovyangfx.cpp
user_setups/esp32s3/waveshare s3 1_69 ctp.ini

The TFT display that I use has an offset.
[https://www.waveshare.com/esp32-s3-touch-lcd-1.69.htm](https://www.waveshare.com/esp32-s3-touch-lcd-1.69.htm)
You can now set the offset in the environment :
```
[env:foobar]
build_flags =
-D ST7789_DRIVER=1
-D TFT_OFFSET_X=0
-D TFT_OFFSET_Y=20
```

add lovyangfx custom offset for tft

---

user_setups/esp32/huzzah32-v2-featherwing-35.ini

This is simply to add a config for using the adafruit huzzah32 v2 with the original featherwing 3.5"

add config for huzza32 v2 with original featherwing

---

user_setups/esp32s3/sunton-esp32-s3-tft.ini

Corrected the size of the touch screen to match the screen size. Otherwise the touch is not really usable. I found the fix in this [Discussion on github](https://github.com/HASwitchPlate/openHASP/discussions/574).

Sunton ESP32-8048S043C touch size adapted to screen size

---

src/drv/tft/tft_driver_lovyangfx.cpp
user_setups/esp32s3/sunton-esp32-2432s024.ini

These are changes based on PR #750 and those contributed in issue #555 after testing with an esp32-2432s024r board
(2.4 inch resistive with one USB-C port)
- **Add sunton esp32-2432s024{r,c}**
- **Working esp32-2432s024r_4MB support**

Add support for sunton esp32-2432s024{r,c}

---

src/dev/esp32/esp32.cpp
src/dev/esp32/esp32.h
src/dev/esp32/twatch.cpp
src/dev/esp32/twatch.h
user_setups/esp32/ttgo-t-watch.ini

Support for the T-Watch PMIC was cut down significantly from what I originally planned - it now consists of turning on the power for the backlight on boot without anything further. 
The T-Watch 2020 V1 hardware variant also ties the Vcc of the display controller to the backlight power - dimming could make it act weirdly and switching off power would require re-initialising the display when switched back on.
The T-Watch devices are not first-class citizens for OpenHASP, but I don't think it matters - this isn't the software to be running on something battery powered anyway. This does at least update the existing configs and adds the PMIC support to make them at least usable.

Update T-Watch support (add PMIC support)

---

src/dev/esp32/esp32.cpp
user_setups/esp32s3/lanbon_l9.ini

* Added flag for Lanbon L9, to control available GPIO pins for L9 with ESP32-S3-N16R2 module with quad-PSRAM

Added exception for Lanbon L9 GPIO

---

user_setups/esp32/esp32-2432s022c.ini

The previous 921600 speed never worked for me (tested with 2 different USB-C cables)
Reverting to 460800 for reliability

Slower (reliable) upload speed for esp32-2432s022c

---

user_setups/esp32s3/sunton-esp32-s3-tft.ini

https://github.com/HASwitchPlate/openHASP/issues/896
Based on @Rolibaer's changes and on
https://github.com/limpens/esp32-8048S043/blob/main/main/lcd.h
e3ae1e6abfec13f98749c9f9ec1adfaa9bde64af
Update 4.3 model's settings along with touch.

esp32s3: esp32-8048S043: fix display and touch for 4.3 version
